//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""deca15c1-32f1-4b22-8b2d-b0312a57b907"",
            ""actions"": [
                {
                    ""name"": ""Evolve"",
                    ""type"": ""Button"",
                    ""id"": ""118609b7-9f17-4b64-9ea9-4d97f0ce8495"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kill1"",
                    ""type"": ""Button"",
                    ""id"": ""981e9b6e-b572-42ef-b6c2-a26d2219f8ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kill2"",
                    ""type"": ""Button"",
                    ""id"": ""d74312fd-e8e7-45b8-a366-5c9d73ea2f66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kill3"",
                    ""type"": ""Button"",
                    ""id"": ""9c04e540-bbe9-4ee6-91c9-9fefeb0d7616"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kill4"",
                    ""type"": ""Button"",
                    ""id"": ""d8553d65-f32c-4a5c-8ea1-5e2f6c3deb06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""350d8a36-5366-4470-bfa3-9cd3458df5bd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Evolve"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6acdfc0-9add-46e6-9368-77cceb22f1e5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Kill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a16301f2-6709-496b-9d09-02976693b149"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Kill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bd77a16-610e-42a0-8e70-a5ae7e0d19d8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Kill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1a1e99d-a916-4dce-8e44-f3fc8ae03979"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Kill4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard and Mouse"",
            ""bindingGroup"": ""Keyboard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Evolve = m_Player.FindAction("Evolve", throwIfNotFound: true);
        m_Player_Kill1 = m_Player.FindAction("Kill1", throwIfNotFound: true);
        m_Player_Kill2 = m_Player.FindAction("Kill2", throwIfNotFound: true);
        m_Player_Kill3 = m_Player.FindAction("Kill3", throwIfNotFound: true);
        m_Player_Kill4 = m_Player.FindAction("Kill4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Evolve;
    private readonly InputAction m_Player_Kill1;
    private readonly InputAction m_Player_Kill2;
    private readonly InputAction m_Player_Kill3;
    private readonly InputAction m_Player_Kill4;
    public struct PlayerActions
    {
        private @InputMaster m_Wrapper;
        public PlayerActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @Evolve => m_Wrapper.m_Player_Evolve;
        public InputAction @Kill1 => m_Wrapper.m_Player_Kill1;
        public InputAction @Kill2 => m_Wrapper.m_Player_Kill2;
        public InputAction @Kill3 => m_Wrapper.m_Player_Kill3;
        public InputAction @Kill4 => m_Wrapper.m_Player_Kill4;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Evolve.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEvolve;
                @Evolve.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEvolve;
                @Evolve.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEvolve;
                @Kill1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill1;
                @Kill1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill1;
                @Kill1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill1;
                @Kill2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill2;
                @Kill2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill2;
                @Kill2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill2;
                @Kill3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill3;
                @Kill3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill3;
                @Kill3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill3;
                @Kill4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill4;
                @Kill4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill4;
                @Kill4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKill4;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Evolve.started += instance.OnEvolve;
                @Evolve.performed += instance.OnEvolve;
                @Evolve.canceled += instance.OnEvolve;
                @Kill1.started += instance.OnKill1;
                @Kill1.performed += instance.OnKill1;
                @Kill1.canceled += instance.OnKill1;
                @Kill2.started += instance.OnKill2;
                @Kill2.performed += instance.OnKill2;
                @Kill2.canceled += instance.OnKill2;
                @Kill3.started += instance.OnKill3;
                @Kill3.performed += instance.OnKill3;
                @Kill3.canceled += instance.OnKill3;
                @Kill4.started += instance.OnKill4;
                @Kill4.performed += instance.OnKill4;
                @Kill4.canceled += instance.OnKill4;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardandMouseSchemeIndex = -1;
    public InputControlScheme KeyboardandMouseScheme
    {
        get
        {
            if (m_KeyboardandMouseSchemeIndex == -1) m_KeyboardandMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and Mouse");
            return asset.controlSchemes[m_KeyboardandMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnEvolve(InputAction.CallbackContext context);
        void OnKill1(InputAction.CallbackContext context);
        void OnKill2(InputAction.CallbackContext context);
        void OnKill3(InputAction.CallbackContext context);
        void OnKill4(InputAction.CallbackContext context);
    }
}
